services:
  - type: web
    name: bankist-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bankist.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bankist.settings
      - key: PYTHON_VERSION
        value: 3.11
