# Generated by Django 5.2.4 on 2025-07-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='User',
            new_name='user',
        ),
    ]
